http:
  routers:
    beacon-api:
      rule: "Host(`beacon-api.ethspec.tools`)"
      entryPoints:
        - websecure
      service: beacon-api
      middlewares:
        - cors
      tls:
        certResolver: letsencrypt

  middlewares:
    cors:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
        accessControlAllowHeaders:
          - "*"
        accessControlAllowOriginList:
          - "https://jtraglia.github.io"
        accessControlMaxAge: 86400

  services:
    beacon-api:
      loadBalancer:
        servers:
          - url: "http://192.168.4.137:5052"
        responseForwarding:
          flushInterval: "-1"
